name: bouncy_button
description: A highly customizable Flutter button widget with engaging 3D depth effects, smooth animations, and extensive styling options.
version: 1.0.1
homepage: https://github.com/Ibrahim-Lokman/bouncy_button
repository: https://github.com/Ibrahim-Lokman/bouncy_button
issue_tracker: https://github.com/Ibrahim-Lokman/bouncy_button/issues
documentation: https://github.com/Ibrahim-Lokman/bouncy_button/blob/main/README.md

environment:
  sdk: ^3.6.0
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

topics:
  - button
  - widget
  - animation
  - material-design
